### ISSUE TITLE
np.abs vs np.sum

### ISSUE THREAD

**Issue by lilyminium** [martinstroet/trapz_errors#1]
Hi there, thank you for this helpful script! I was just rewriting it for Python 3 and had a question about this part:

https://github.com/ATB-UQ/trapz_errors/blob/05019d9dd6a9e3af4d2e406c8069564bb4c469fc/calculate_error.py#L85

This line seems to set the `gap_x`, etc. to the one of the `backwards` and `forward` that has the highest error, right? I just wonder if the `np.abs(np.sum())` is the correct way around -- should it be `np.sum(np.abs())` ? In the former, errors of different signs cancel each other out; in the latter, only the magnitude matters. Apologies if I'm misunderstanding this part of the code.

**Comment by martinstroet** [comment]
Hi, glad you have found it useful! I look forward to the Python 3 version pull request :)

I had to look this up again to make sure it wasn't a bug, see section 2.2.3 of: https://espace.library.uq.edu.au/view/UQ:60b93e7/s4122143_final_thesis.pdf. The cancelation of errors is part of the method.

**Comment by lilyminium** [comment]
Awesome, thank you for the clarification! :)
